version: '3.8'

services:
  backend:
    build: ./backend
    container_name: truyen_backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/truyen_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: truyen_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=truyen_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: truyen_redis
    ports:
      - "6400:6379"

volumes:
  postgres_data:
